# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a288953f3cdf33c181f1c230fee65dfb5ea2387dc6cdd0f8af423912d4661f086fd5d55048cb0a5f73d84375b6ef58988983c4d86e8cc5bacacb925f64876012

test:
  secret_key_base: 9fbe5114f109f43fdd5632af824b81692f098d9cc746b9bad1502ae4017701e411ec97c8d3a5ce1d6fe621d6daae216a18764efed76c778f91b1b12f75c5492b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
